"""
quarantine_duplicates.py – Move duplicate/near-duplicate images to the 
quarantine subfolder within TrainImages based on the 
report generated by find_duplicates.py.

Destination Structure:
  TrainImages/
    duplicates/
      exact/
        0_Recyclable/   <- keep the original class structure
        1_Electronic/
        2_Organic/
      near/
        0_Recyclable/
        ...

Use --dry-run to run preview without actually moving the files.
"""

import argparse
import json
import shutil
import sys
from pathlib import Path


def resolve_quarantine_dest(
    file_path: Path,
    data_dir: Path,
    quarantine_root: Path,
    dup_type: str,          # "exact" or "near"
) -> Path:
    """
    Determine the destination path within the quarantine folder,
    maintaining the original class subfolder structure..
    """
    try:
        rel = file_path.relative_to(data_dir)
    except ValueError:
        rel = Path(file_path.name)

    return quarantine_root / dup_type / rel


def move_file(src: Path, dst: Path, dry_run: bool) -> bool:
    """
    Move src ke dst. eturn True if success.
    If dry_run=True, only print without moving.
    """
    if not src.exists():
        print(f"  [SKIP] Not found: {src}")
        return False

    if dry_run:
        print(f"  [DRY-RUN] {src.name}  ->  {dst}")
        return True

    dst.parent.mkdir(parents=True, exist_ok=True)
    try:
        shutil.move(str(src), str(dst))
        return True
    except Exception as e:
        print(f"  [ERROR] Faile to move {src.name}: {e}", file=sys.stderr)
        return False


def main():
    script_dir = Path(__file__).resolve().parent
    default_report = script_dir / "duplicates_report.json"
    default_data_dir = script_dir.parents[1] / "TrainImages"

    ap = argparse.ArgumentParser(
        description="Pindahkan file duplikat ke folder karantina berdasarkan duplicates_report.json."
    )
    ap.add_argument("--report", default=str(default_report),
                    help="Path to duplicates_report.json (default: output find_duplicates.py)")
    ap.add_argument("--data-dir", default=str(default_data_dir),
                    help="Dataset directory (default: TrainImages)")
    ap.add_argument("--quarantine-dir", default=None,
                    help="Destination quarantine folder (default: <data-dir>/duplicates/)")
    ap.add_argument("--dry-run", action="store_true",
                    help="Preview the file that will be moved without actually moving it.")
    args = ap.parse_args()

    report_path = Path(args.report)
    if not report_path.exists():
        print(f"Error: Report '{report_path}' not found.", file=sys.stderr)
        print("Maybe run find_duplicates.py first.", file=sys.stderr)
        sys.exit(1)

    data_dir = Path(args.data_dir)
    quarantine_root = Path(args.quarantine_dir) if args.quarantine_dir else data_dir / "duplicates"

    with open(report_path, "r", encoding="utf-8") as f:
        report = json.load(f)

    summary = report.get("summary", {})
    total_to_move = summary.get("total_to_move", 0)

    if total_to_move == 0:
        print("No duplicate files to be moved according to the report.")
        sys.exit(0)

    mode_label = "[DRY-RUN] " if args.dry_run else ""
    print(f"{mode_label}Moving duplicate files to: {quarantine_root.resolve()}")
    print(f"Total files to move: {total_to_move}\n")

    moved_exact = 0
    moved_near = 0
    skipped = 0

    # -----------------------------------------------------------------------
    # exact duplicates
    # -----------------------------------------------------------------------
    exact_groups = report.get("exact_duplicate_groups", [])
    if exact_groups:
        print(f"{'=' * 55}")
        print(f"Exact Duplicates ({sum(len(g['to_move']) for g in exact_groups)} file)")
        print(f"{'=' * 55}")

    for group in exact_groups:
        keeper_path = Path(group["keeper"])
        print(f"  [KEEP]  {keeper_path.parent.name}/{keeper_path.name}")
        for to_move_str in group["to_move"]:
            src = Path(to_move_str)
            dst = resolve_quarantine_dest(src, data_dir, quarantine_root, "exact")
            ok = move_file(src, dst, args.dry_run)
            if ok:
                moved_exact += 1
            else:
                skipped += 1

    # -----------------------------------------------------------------------
    # near duplicates
    # -----------------------------------------------------------------------
    near_pairs = report.get("near_duplicate_pairs", [])

    # Deduplication: one file may appear in many pairs 
    # Collect all "to_move" files that have not been processed yet (not exact dup)
    exact_moved_set = set()
    for group in exact_groups:
        exact_moved_set.update(group["to_move"])

    near_to_move: dict[str, str] = {}  # to_move_path -> keeper_path (str)
    for pair in near_pairs:
        to_move_str = pair["to_move"]
        if to_move_str not in exact_moved_set and to_move_str not in near_to_move:
            near_to_move[to_move_str] = pair["keeper"]

    if near_to_move:
        print(f"\n{'=' * 55}")
        print(f"Near Duplicates ({len(near_to_move)} unique files)")
        print(f"{'=' * 55}")

    for to_move_str, keeper_str in near_to_move.items():
        src = Path(to_move_str)
        keeper_path = Path(keeper_str)
        print(f"  [KEEP]  {keeper_path.parent.name}/{keeper_path.name}  "
              f"(dist={next((p['hamming_distance'] for p in near_pairs if p['to_move'] == to_move_str), '?')})")
        dst = resolve_quarantine_dest(src, data_dir, quarantine_root, "near")
        ok = move_file(src, dst, args.dry_run)
        if ok:
            moved_near += 1
        else:
            skipped += 1

    # -----------------------------------------------------------------------
    # Final Summary
    # -----------------------------------------------------------------------
    total_moved = moved_exact + moved_near
    print(f"\n{'=' * 55}")
    print(f"{'[DRY-RUN] ' if args.dry_run else ''}Quarantine Summary")
    print(f"{'-' * 55}")
    print(f"Exact duplicate moved : {moved_exact}")
    print(f"Near-duplicate moved  : {moved_near}")
    print(f"Skipped (not exist)   : {skipped}")
    print(f"Total moved           : {total_moved}")
    if not args.dry_run and total_moved > 0:
        print(f"\nQuarantine folder: {quarantine_root.resolve()}")
        print(f"  duplicates/exact/ -> exact duplicates")
        print(f"  duplicates/near/  -> near duplicates")
    print(f"{'=' * 55}")

    if args.dry_run:
        print("\n[DRY-RUN complete] No files were actually moved.")
        print("Run without --dry-run to move files permanently.")


if __name__ == "__main__":
    main()
